spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-root.xml
  datasource:
    url: jdbc:postgresql://193.40.255.30:5432/postgres
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: none
